#!/bin/bash
set -euo pipefail

ROLE="$1"
SCHEMA="${2:-public}"

"$(dirname "$0")/role-read-only.sh" "$1" "$2"

cat <<SQL
IF
EXISTS (SELECT * FROM pg_catalog.pg_roles WHERE rolname = '$ROLE')

THEN
    REVOKE INSERT  ON ALL TABLES    IN SCHEMA     $SCHEMA FROM $ROLE ;
    REVOKE UPDATE  ON ALL TABLES    IN SCHEMA     $SCHEMA FROM $ROLE ;

ELSE
    CREATE ROLE $ROLE;

END IF ;

GRANT UPDATE    ON ALL TABLES    IN SCHEMA     $SCHEMA TO $ROLE ;
GRANT INSERT    ON ALL TABLES    IN SCHEMA     $SCHEMA TO $ROLE ;

ALTER DEFAULT PRIVILEGES IN SCHEMA $SCHEMA GRANT INSERT ON TABLES    TO $ROLE;
ALTER DEFAULT PRIVILEGES IN SCHEMA $SCHEMA GRANT UPDATE ON TABLES    TO $ROLE;
SQL
