#!/bin/bash
set -euo pipefail

ROLE="$1"
SCHEMA="${2:-public}"

cat <<SQL
IF
    EXISTS (SELECT * FROM pg_catalog.pg_user WHERE usename = '$ROLE')

    THEN
        REVOKE USAGE   ON ALL SEQUENCES IN SCHEMA     $SCHEMA FROM $ROLE ;
        REVOKE SELECT  ON ALL TABLES    IN SCHEMA     $SCHEMA FROM $ROLE ;
        REVOKE UPDATE  ON ALL TABLES    IN SCHEMA     $SCHEMA FROM $ROLE ;
        REVOKE USAGE   ON SCHEMA                      $SCHEMA FROM $ROLE ;
        REVOKE EXECUTE ON ALL FUNCTIONS IN SCHEMA     $SCHEMA FROM $ROLE ;

    ELSE
        CREATE ROLE $ROLE;

    END IF ;

    GRANT USAGE     ON                  SCHEMA     $SCHEMA TO $ROLE ;
    GRANT SELECT    ON ALL TABLES    IN SCHEMA     $SCHEMA TO $ROLE ;
    GRANT UPDATE    ON ALL TABLES    IN SCHEMA     $SCHEMA TO $ROLE ;
    GRANT USAGE     ON ALL SEQUENCES IN SCHEMA     $SCHEMA TO $ROLE ;
    GRANT EXECUTE   ON ALL FUNCTIONS IN SCHEMA     $SCHEMA TO $ROLE ;
SQL
