#!/bin/bash
set -euo pipefail

ROLE="$1"
SCHEMA="${2:-public}"

cat <<SQL
IF
EXISTS (SELECT * FROM pg_catalog.pg_roles WHERE rolname = '$ROLE')

THEN
    REVOKE ALL PRIVILEGES  ON ALL TABLES    IN SCHEMA     $SCHEMA FROM $ROLE ;
    REVOKE ALL PRIVILEGES  ON ALL SEQUENCES IN SCHEMA     $SCHEMA FROM $ROLE ;
    REVOKE ALL PRIVILEGES  ON ALL FUNCTIONS IN SCHEMA     $SCHEMA FROM $ROLE ;

    ALTER DEFAULT PRIVILEGES IN SCHEMA $SCHEMA REVOKE ALL PRIVILEGES ON TABLES FROM $ROLE ;
    ALTER DEFAULT PRIVILEGES IN SCHEMA $SCHEMA REVOKE ALL PRIVILEGES ON SEQUENCES FROM $ROLE ;
    ALTER DEFAULT PRIVILEGES IN SCHEMA $SCHEMA REVOKE ALL PRIVILEGES ON FUNCTIONS FROM $ROLE ;
ELSE
    CREATE ROLE $ROLE;

END IF ;

GRANT ALL PRIVILEGES   ON ALL TABLES    IN SCHEMA     $SCHEMA TO $ROLE ;
GRANT ALL PRIVILEGES   ON ALL SEQUENCES IN SCHEMA     $SCHEMA TO $ROLE ;
GRANT ALL PRIVILEGES   ON ALL FUNCTIONS IN SCHEMA     $SCHEMA TO $ROLE ;

ALTER DEFAULT PRIVILEGES IN SCHEMA $SCHEMA GRANT ALL PRIVILEGES ON TABLES    TO $ROLE;
ALTER DEFAULT PRIVILEGES IN SCHEMA $SCHEMA GRANT ALL PRIVILEGES ON SEQUENCES TO $ROLE;
ALTER DEFAULT PRIVILEGES IN SCHEMA $SCHEMA GRANT ALL PRIVILEGES ON FUNCTIONS TO $ROLE;
SQL
